services:
    graphwiki_user.registration.form.type:
        class: Binaerpiloten\GraphWikiBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: graphwiki_user_registration }
    graphwiki_user.profile.form.type:
        class: Binaerpiloten\GraphWikiBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: graphwiki_user_profile }
    graphwiki.twig.token_extension:
        class: Binaerpiloten\GraphWikiBundle\Twig\TokenExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }            